### ISSUE TITLE
Having integers as node names induces error while visualizing

### ISSUE THREAD

**Issue by user1246638** [uzhdag/pathpy#26]
Message is the following:
\pathpy\visualisation\html.py in fix_node_name(v)
    236     # prefix nodes starting with number as such IDs are not supported in HTML5
    237     def fix_node_name(v):
--> 238         if v[0].isdigit():
    239             return "n_" + v
    240         return v
Error is :TypeError: 'int' object is not subscriptable .

Code that reproduces the error:

import pathpy as pp
n = pp.Network()
n.add_edge(1,2)
n

**Comment by IngoScholtes** [comment]
Indeed, this is an issue. Thanks for noticing!

We're working on it and you shall hear more shortly.

**Comment by IngoScholtes** [comment]
fixed in ac653
