### ISSUE TITLE
Installing network2tikz adds old version of pathpy to the anaconda site-packages folder

### ISSUE THREAD

**Issue by user1246638** [uzhdag/pathpy#33]
I have pathpy installed as editable.
This folder has somehow priority over the folder where I have the new version.
Tried it on two computers. To solve the issue, you need to delete the folder pathpy in anaconda3\lib\site-packages\.

**Comment by hackl** [comment]
This issue has been fixed (https://github.com/hackl/network2tikz/commit/d8a4daac11aed9c4fc2a55b75de9ba24d65296b2) see also https://github.com/hackl/network2tikz/issues/4

**Comment by IngoScholtes** [comment]
Thanks @hackl for the fix!
