### ISSUE TITLE
Type error when creating a k regular network

### ISSUE THREAD

**Issue by Deerest** [uzhdag/pathpy#35]
when running pp.algorithms.random_graphs.random_k_regular(100,5)  the following error occurs

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-d54c435745b7> in <module>()
----> 1 pp.algorithms.random_graphs.random_k_regular(100,5)

~\Documents\pathpy\pathpy\algorithms\random_graphs.py in random_k_regular(n, k, self_loops, node_names)
    179     """
    180     assert n*k%2 == 0, 'Error: parameters lead to non-graphic degree sequence.'
--> 181     return molloy_reed([k]*n, self_loops, node_names)
    182 
    183 

~\Documents\pathpy\pathpy\algorithms\random_graphs.py in molloy_reed(degree_sequence, node_names, self_loops, multi_edges)
    128     if node_names is None:
    129         node_names = [str(x) for x in range(n)]
--> 130     assert len(node_names) >= n, 'Error: Number of node names not matching degree sequence length'
    131 
    132     network = Network(directed=False)

TypeError: object of type 'bool' has no len()

**Comment by advand** [comment]
This occurs due to an argument ordering error, self_loops and node_names are interchanged in the call: `return molloy_reed([k]*n, self_loops, node_names)`
Function signature: `def molloy_reed(degree_sequence, node_names=None, self_loops=True, multi_edges=False):`

Call in
