### ISSUE TITLE
Bug in path_extraction.paths_from_temporal_network

### ISSUE THREAD

**Issue by gi0na** [uzhdag/pathpy#43]
When two or more edges have the same timestamp in a temporal network, only the first one is used to generate a path.

Minimal code:

`t = pp.TemporalNetwork()`
`t.add_edge(source="a", target="b", ts=1)`
`t.add_edge(source="b", target="c", ts=2)`
`t.add_edge(source="b", target="d", ts=2)`

`paths = pp.path_extraction.paths_from_temporal_network(t, delta=10)`
`network = pp.HigherOrderNetwork(paths=paths, k=2)`
`network.edges`

This results in:
> defaultdict(dict, {('a,b', 'b,c'): {'weight': array([ 0.,  1.])}})

However, we should have got something like this, as the two edges are simultaneous:
> defaultdict(dict,
            {('a,b', 'b,c'): {'weight': array([ 1.,  0.])},
             ('a,b', 'b,d'): {'weight': array([ 1.,  0.])}})

**Comment by IngoScholtes** [comment]
Thanks, Giona! 

While this is expected and documented behavior, I agree that the behavior (and the naming of the function) is confusing. The documentation also doesn't make clear that also for simultaneous edges only the first edge is used. 

For the proper extraction of all paths, the method `paths_from_temporal_network_dag` should be used. I will add a deprecation notice and reroute this method to `paths_from_temporal_network_dag`.
