### ISSUE TITLE
Serialisation of paths object to pickle or similar for fast reloading

### ISSUE THREAD

**Issue by narnolddd** [uzhdag/pathpy#61]
First off, apologies if this is something I totally missed when I was looking through the docs!

It would be fantastic to be able to "save" a paths object as a pickle or similar so it would be faster to reload it after reading it in the first time from some paths data. At the moment I have a big dataset and it takes about 2-3 mins to make a paths object out of it, would be handy to be able to just do this once and then reload it quickly from bytecode afterwards.

I would imagine this looking something like 
```python
# reading data the first time as normal
p = pp.paths()
for path in path_data:
  p.add_path(path)

# serialise to pickle
p.save_pickle('path_object.p')

# reloading
p_2 = pp.read_pickle('path_object.p')
```

Thanks and let me know if I can help in some way!

**Comment by verginer** [comment]
Hi @narnolddd you can pickle a Paths object alrady, no need to have a dedicated interface for it. Here an example

```python
import pathpy as pp
import pickle

p = pp.Paths()

p.add_path((1, 2, 3, 4, 5))

with open('pp.pkl', 'wb') as f:
    pickle.dump(p, f)
    
with open('pp.pkl', 'rb') as f:
    p2 = pickle.load(f)

assert p.paths.keys() == p2.paths.keys()
```
